title: "[Meeting Notes] "
body:  
  - type: textarea
    attributes:
      label: "The timeline:"
  - type: textarea
    attributes:
      label: "What are the most important topics discussed?"
  - type: textarea
    attributes:
      label: "What was decided?"
