title: "[Meeting] <Topic>"
labels: ["meeting"]
body:
  - type: markdown
    attributes:
      value: |
        # 📝 Pre-Meeting Information
        Fill in this section before the meeting with relevant details such as the agenda, participants, and objectives.

  - type: textarea
    id: meeting-info
    attributes:
      label: "📋 Meeting Information"
      description: "Enter details such as date, time, location, agenda, and goals."
      placeholder: |
        - **Date**: YYYY-MM-DD
        - **Time**: HH:MM
        - **Location**: Zoom/Office
        - **Agenda**:
          - Topic 1
          - Topic 2
      value: |
        - **Date**: 
        - **Time**: 
        - **Location**: 
        - **Agenda**: 

  - type: textarea
    id: attendees
    attributes:
      label: "👥 Attendees"
      description: "List all participants in the meeting."
      placeholder: |
        - @username1
        - @username2
        - @username3
      value: |
        - 

  - type: markdown
    attributes:
      value: |
        ---

        ## 📌 Meeting Notes
        Use this section to capture important decisions, action items, and responsibilities.

  - type: textarea
    id: meeting-notes
    attributes:
      label: "📖 Notes & Outcomes"
      description: "Document key points, decisions, and action items."
      placeholder: |
        - **Key Decisions**:
          - Decision 1
          - Decision 2
        - **Action Items**:
          - [ ] Task 1 - Assigned to @user
          - [ ] Task 2 - Assigned to @user
      value: |
        - **Key Decisions**: 
        - **Action Items**: 

  - type: markdown
    attributes:
      value: |
        ---

        ## 🚀 Next Steps
        Outline the upcoming steps or follow-up tasks after the meeting.

  - type: textarea
    id: next-steps
    attributes:
      label: "🔜 Next Steps"
      description: "Define what needs to happen next and assign responsibilities."
      placeholder: |
        - [ ] Step 1 - Assigned to @user
        - [ ] Step 2 - Assigned to @user
        - [ ] Step 3 - Assigned to @user
      value: |
        - 
